name: Release

on:
  push:
    tags:
      - "v*" # "v1.0.0" などのタグがプッシュされたときに実行されます

jobs:
  release:
    runs-on: windows-latest
    permissions:
        contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          # タグ名(例: v1.0.0)から "v" を取り除いて 1.0.0 を抽出する
          $tag = "${{ github.ref_name }}"
          $version = $tag.TrimStart("v")
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Compile Inno Setup Installer
        run: |
          # .iss ファイルのパスを .github\installer 配下に変更 (先頭に & を追加)
          & "C:\Program Files (x86)\Inno Setup 6\iscc.exe" "/DMyAppVersion=$env:VERSION" ".github\installer\PPTVbaAssist.iss"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/PPTVbaAssist.ppam
            Output/PPTVbaAssist_Setup_*.exe
          generate_release_notes: true